// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bellman_ford_bellman_ford_Pipeline_VITIS_LOOP_46_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dist_0_address0,
        dist_0_ce0,
        dist_0_we0,
        dist_0_d0,
        dist_3_address0,
        dist_3_ce0,
        dist_3_we0,
        dist_3_d0,
        dist_2_address0,
        dist_2_ce0,
        dist_2_we0,
        dist_2_d0,
        dist_1_address0,
        dist_1_ce0,
        dist_1_we0,
        dist_1_d0,
        updated_dist_128_reload,
        updated_dist_129_reload,
        updated_dist_130_reload,
        updated_dist_131_reload,
        updated_dist_132_reload,
        updated_dist_133_reload,
        updated_dist_134_reload,
        updated_dist_135_reload,
        updated_dist_136_reload,
        updated_dist_137_reload,
        updated_dist_138_reload,
        updated_dist_139_reload,
        updated_dist_140_reload,
        updated_dist_141_reload,
        updated_dist_142_reload,
        updated_dist_143_reload,
        updated_dist_144_reload,
        updated_dist_145_reload,
        updated_dist_146_reload,
        updated_dist_147_reload,
        updated_dist_148_reload,
        updated_dist_149_reload,
        updated_dist_150_reload,
        updated_dist_151_reload,
        updated_dist_152_reload,
        updated_dist_153_reload,
        updated_dist_154_reload,
        updated_dist_155_reload,
        updated_dist_156_reload,
        updated_dist_157_reload,
        updated_dist_158_reload,
        updated_dist_159_reload,
        updated_dist_160_reload,
        updated_dist_161_reload,
        updated_dist_162_reload,
        updated_dist_163_reload,
        updated_dist_164_reload,
        updated_dist_165_reload,
        updated_dist_166_reload,
        updated_dist_167_reload,
        updated_dist_168_reload,
        updated_dist_169_reload,
        updated_dist_170_reload,
        updated_dist_171_reload,
        updated_dist_172_reload,
        updated_dist_173_reload,
        updated_dist_174_reload,
        updated_dist_175_reload,
        updated_dist_176_reload,
        updated_dist_177_reload,
        updated_dist_178_reload,
        updated_dist_179_reload,
        updated_dist_180_reload,
        updated_dist_181_reload,
        updated_dist_182_reload,
        updated_dist_183_reload,
        updated_dist_184_reload,
        updated_dist_185_reload,
        updated_dist_186_reload,
        updated_dist_187_reload,
        updated_dist_188_reload,
        updated_dist_189_reload,
        updated_dist_190_reload,
        updated_dist_191_reload,
        updated_dist_192_reload,
        updated_dist_193_reload,
        updated_dist_194_reload,
        updated_dist_195_reload,
        updated_dist_196_reload,
        updated_dist_197_reload,
        updated_dist_198_reload,
        updated_dist_199_reload,
        updated_dist_200_reload,
        updated_dist_201_reload,
        updated_dist_202_reload,
        updated_dist_203_reload,
        updated_dist_204_reload,
        updated_dist_205_reload,
        updated_dist_206_reload,
        updated_dist_207_reload,
        updated_dist_208_reload,
        updated_dist_209_reload,
        updated_dist_210_reload,
        updated_dist_211_reload,
        updated_dist_212_reload,
        updated_dist_213_reload,
        updated_dist_214_reload,
        updated_dist_215_reload,
        updated_dist_216_reload,
        updated_dist_217_reload,
        updated_dist_218_reload,
        updated_dist_219_reload,
        updated_dist_220_reload,
        updated_dist_221_reload,
        updated_dist_222_reload,
        updated_dist_223_reload,
        updated_dist_224_reload,
        updated_dist_225_reload,
        updated_dist_226_reload,
        updated_dist_227_reload,
        updated_dist_228_reload,
        updated_dist_229_reload,
        updated_dist_230_reload,
        updated_dist_231_reload,
        updated_dist_232_reload,
        updated_dist_233_reload,
        updated_dist_234_reload,
        updated_dist_235_reload,
        updated_dist_236_reload,
        updated_dist_237_reload,
        updated_dist_238_reload,
        updated_dist_239_reload,
        updated_dist_240_reload,
        updated_dist_241_reload,
        updated_dist_242_reload,
        updated_dist_243_reload,
        updated_dist_244_reload,
        updated_dist_245_reload,
        updated_dist_246_reload,
        updated_dist_247_reload,
        updated_dist_248_reload,
        updated_dist_249_reload,
        updated_dist_250_reload,
        updated_dist_251_reload,
        updated_dist_252_reload,
        updated_dist_253_reload,
        updated_dist_254_reload,
        updated_dist_255_reload
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] dist_0_address0;
output   dist_0_ce0;
output   dist_0_we0;
output  [31:0] dist_0_d0;
output  [4:0] dist_3_address0;
output   dist_3_ce0;
output   dist_3_we0;
output  [31:0] dist_3_d0;
output  [4:0] dist_2_address0;
output   dist_2_ce0;
output   dist_2_we0;
output  [31:0] dist_2_d0;
output  [4:0] dist_1_address0;
output   dist_1_ce0;
output   dist_1_we0;
output  [31:0] dist_1_d0;
input  [31:0] updated_dist_128_reload;
input  [31:0] updated_dist_129_reload;
input  [31:0] updated_dist_130_reload;
input  [31:0] updated_dist_131_reload;
input  [31:0] updated_dist_132_reload;
input  [31:0] updated_dist_133_reload;
input  [31:0] updated_dist_134_reload;
input  [31:0] updated_dist_135_reload;
input  [31:0] updated_dist_136_reload;
input  [31:0] updated_dist_137_reload;
input  [31:0] updated_dist_138_reload;
input  [31:0] updated_dist_139_reload;
input  [31:0] updated_dist_140_reload;
input  [31:0] updated_dist_141_reload;
input  [31:0] updated_dist_142_reload;
input  [31:0] updated_dist_143_reload;
input  [31:0] updated_dist_144_reload;
input  [31:0] updated_dist_145_reload;
input  [31:0] updated_dist_146_reload;
input  [31:0] updated_dist_147_reload;
input  [31:0] updated_dist_148_reload;
input  [31:0] updated_dist_149_reload;
input  [31:0] updated_dist_150_reload;
input  [31:0] updated_dist_151_reload;
input  [31:0] updated_dist_152_reload;
input  [31:0] updated_dist_153_reload;
input  [31:0] updated_dist_154_reload;
input  [31:0] updated_dist_155_reload;
input  [31:0] updated_dist_156_reload;
input  [31:0] updated_dist_157_reload;
input  [31:0] updated_dist_158_reload;
input  [31:0] updated_dist_159_reload;
input  [31:0] updated_dist_160_reload;
input  [31:0] updated_dist_161_reload;
input  [31:0] updated_dist_162_reload;
input  [31:0] updated_dist_163_reload;
input  [31:0] updated_dist_164_reload;
input  [31:0] updated_dist_165_reload;
input  [31:0] updated_dist_166_reload;
input  [31:0] updated_dist_167_reload;
input  [31:0] updated_dist_168_reload;
input  [31:0] updated_dist_169_reload;
input  [31:0] updated_dist_170_reload;
input  [31:0] updated_dist_171_reload;
input  [31:0] updated_dist_172_reload;
input  [31:0] updated_dist_173_reload;
input  [31:0] updated_dist_174_reload;
input  [31:0] updated_dist_175_reload;
input  [31:0] updated_dist_176_reload;
input  [31:0] updated_dist_177_reload;
input  [31:0] updated_dist_178_reload;
input  [31:0] updated_dist_179_reload;
input  [31:0] updated_dist_180_reload;
input  [31:0] updated_dist_181_reload;
input  [31:0] updated_dist_182_reload;
input  [31:0] updated_dist_183_reload;
input  [31:0] updated_dist_184_reload;
input  [31:0] updated_dist_185_reload;
input  [31:0] updated_dist_186_reload;
input  [31:0] updated_dist_187_reload;
input  [31:0] updated_dist_188_reload;
input  [31:0] updated_dist_189_reload;
input  [31:0] updated_dist_190_reload;
input  [31:0] updated_dist_191_reload;
input  [31:0] updated_dist_192_reload;
input  [31:0] updated_dist_193_reload;
input  [31:0] updated_dist_194_reload;
input  [31:0] updated_dist_195_reload;
input  [31:0] updated_dist_196_reload;
input  [31:0] updated_dist_197_reload;
input  [31:0] updated_dist_198_reload;
input  [31:0] updated_dist_199_reload;
input  [31:0] updated_dist_200_reload;
input  [31:0] updated_dist_201_reload;
input  [31:0] updated_dist_202_reload;
input  [31:0] updated_dist_203_reload;
input  [31:0] updated_dist_204_reload;
input  [31:0] updated_dist_205_reload;
input  [31:0] updated_dist_206_reload;
input  [31:0] updated_dist_207_reload;
input  [31:0] updated_dist_208_reload;
input  [31:0] updated_dist_209_reload;
input  [31:0] updated_dist_210_reload;
input  [31:0] updated_dist_211_reload;
input  [31:0] updated_dist_212_reload;
input  [31:0] updated_dist_213_reload;
input  [31:0] updated_dist_214_reload;
input  [31:0] updated_dist_215_reload;
input  [31:0] updated_dist_216_reload;
input  [31:0] updated_dist_217_reload;
input  [31:0] updated_dist_218_reload;
input  [31:0] updated_dist_219_reload;
input  [31:0] updated_dist_220_reload;
input  [31:0] updated_dist_221_reload;
input  [31:0] updated_dist_222_reload;
input  [31:0] updated_dist_223_reload;
input  [31:0] updated_dist_224_reload;
input  [31:0] updated_dist_225_reload;
input  [31:0] updated_dist_226_reload;
input  [31:0] updated_dist_227_reload;
input  [31:0] updated_dist_228_reload;
input  [31:0] updated_dist_229_reload;
input  [31:0] updated_dist_230_reload;
input  [31:0] updated_dist_231_reload;
input  [31:0] updated_dist_232_reload;
input  [31:0] updated_dist_233_reload;
input  [31:0] updated_dist_234_reload;
input  [31:0] updated_dist_235_reload;
input  [31:0] updated_dist_236_reload;
input  [31:0] updated_dist_237_reload;
input  [31:0] updated_dist_238_reload;
input  [31:0] updated_dist_239_reload;
input  [31:0] updated_dist_240_reload;
input  [31:0] updated_dist_241_reload;
input  [31:0] updated_dist_242_reload;
input  [31:0] updated_dist_243_reload;
input  [31:0] updated_dist_244_reload;
input  [31:0] updated_dist_245_reload;
input  [31:0] updated_dist_246_reload;
input  [31:0] updated_dist_247_reload;
input  [31:0] updated_dist_248_reload;
input  [31:0] updated_dist_249_reload;
input  [31:0] updated_dist_250_reload;
input  [31:0] updated_dist_251_reload;
input  [31:0] updated_dist_252_reload;
input  [31:0] updated_dist_253_reload;
input  [31:0] updated_dist_254_reload;
input  [31:0] updated_dist_255_reload;

reg ap_idle;
reg dist_0_ce0;
reg dist_0_we0;
reg dist_3_ce0;
reg dist_3_we0;
reg dist_2_ce0;
reg dist_2_we0;
reg dist_1_ce0;
reg dist_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln1027_fu_1150_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln48_fu_1446_p1;
wire   [1:0] trunc_ln48_fu_1432_p1;
reg   [7:0] j_V_1_fu_318;
wire   [7:0] add_ln840_fu_1156_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_j_V;
wire   [31:0] tmp_2_fu_1166_p130;
wire   [6:0] tmp_2_fu_1166_p129;
wire   [4:0] lshr_ln3_fu_1436_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

bellman_ford_mux_1287_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 32 ),
    .din65_WIDTH( 32 ),
    .din66_WIDTH( 32 ),
    .din67_WIDTH( 32 ),
    .din68_WIDTH( 32 ),
    .din69_WIDTH( 32 ),
    .din70_WIDTH( 32 ),
    .din71_WIDTH( 32 ),
    .din72_WIDTH( 32 ),
    .din73_WIDTH( 32 ),
    .din74_WIDTH( 32 ),
    .din75_WIDTH( 32 ),
    .din76_WIDTH( 32 ),
    .din77_WIDTH( 32 ),
    .din78_WIDTH( 32 ),
    .din79_WIDTH( 32 ),
    .din80_WIDTH( 32 ),
    .din81_WIDTH( 32 ),
    .din82_WIDTH( 32 ),
    .din83_WIDTH( 32 ),
    .din84_WIDTH( 32 ),
    .din85_WIDTH( 32 ),
    .din86_WIDTH( 32 ),
    .din87_WIDTH( 32 ),
    .din88_WIDTH( 32 ),
    .din89_WIDTH( 32 ),
    .din90_WIDTH( 32 ),
    .din91_WIDTH( 32 ),
    .din92_WIDTH( 32 ),
    .din93_WIDTH( 32 ),
    .din94_WIDTH( 32 ),
    .din95_WIDTH( 32 ),
    .din96_WIDTH( 32 ),
    .din97_WIDTH( 32 ),
    .din98_WIDTH( 32 ),
    .din99_WIDTH( 32 ),
    .din100_WIDTH( 32 ),
    .din101_WIDTH( 32 ),
    .din102_WIDTH( 32 ),
    .din103_WIDTH( 32 ),
    .din104_WIDTH( 32 ),
    .din105_WIDTH( 32 ),
    .din106_WIDTH( 32 ),
    .din107_WIDTH( 32 ),
    .din108_WIDTH( 32 ),
    .din109_WIDTH( 32 ),
    .din110_WIDTH( 32 ),
    .din111_WIDTH( 32 ),
    .din112_WIDTH( 32 ),
    .din113_WIDTH( 32 ),
    .din114_WIDTH( 32 ),
    .din115_WIDTH( 32 ),
    .din116_WIDTH( 32 ),
    .din117_WIDTH( 32 ),
    .din118_WIDTH( 32 ),
    .din119_WIDTH( 32 ),
    .din120_WIDTH( 32 ),
    .din121_WIDTH( 32 ),
    .din122_WIDTH( 32 ),
    .din123_WIDTH( 32 ),
    .din124_WIDTH( 32 ),
    .din125_WIDTH( 32 ),
    .din126_WIDTH( 32 ),
    .din127_WIDTH( 32 ),
    .din128_WIDTH( 7 ),
    .dout_WIDTH( 32 ))
mux_1287_32_1_1_U265(
    .din0(updated_dist_128_reload),
    .din1(updated_dist_129_reload),
    .din2(updated_dist_130_reload),
    .din3(updated_dist_131_reload),
    .din4(updated_dist_132_reload),
    .din5(updated_dist_133_reload),
    .din6(updated_dist_134_reload),
    .din7(updated_dist_135_reload),
    .din8(updated_dist_136_reload),
    .din9(updated_dist_137_reload),
    .din10(updated_dist_138_reload),
    .din11(updated_dist_139_reload),
    .din12(updated_dist_140_reload),
    .din13(updated_dist_141_reload),
    .din14(updated_dist_142_reload),
    .din15(updated_dist_143_reload),
    .din16(updated_dist_144_reload),
    .din17(updated_dist_145_reload),
    .din18(updated_dist_146_reload),
    .din19(updated_dist_147_reload),
    .din20(updated_dist_148_reload),
    .din21(updated_dist_149_reload),
    .din22(updated_dist_150_reload),
    .din23(updated_dist_151_reload),
    .din24(updated_dist_152_reload),
    .din25(updated_dist_153_reload),
    .din26(updated_dist_154_reload),
    .din27(updated_dist_155_reload),
    .din28(updated_dist_156_reload),
    .din29(updated_dist_157_reload),
    .din30(updated_dist_158_reload),
    .din31(updated_dist_159_reload),
    .din32(updated_dist_160_reload),
    .din33(updated_dist_161_reload),
    .din34(updated_dist_162_reload),
    .din35(updated_dist_163_reload),
    .din36(updated_dist_164_reload),
    .din37(updated_dist_165_reload),
    .din38(updated_dist_166_reload),
    .din39(updated_dist_167_reload),
    .din40(updated_dist_168_reload),
    .din41(updated_dist_169_reload),
    .din42(updated_dist_170_reload),
    .din43(updated_dist_171_reload),
    .din44(updated_dist_172_reload),
    .din45(updated_dist_173_reload),
    .din46(updated_dist_174_reload),
    .din47(updated_dist_175_reload),
    .din48(updated_dist_176_reload),
    .din49(updated_dist_177_reload),
    .din50(updated_dist_178_reload),
    .din51(updated_dist_179_reload),
    .din52(updated_dist_180_reload),
    .din53(updated_dist_181_reload),
    .din54(updated_dist_182_reload),
    .din55(updated_dist_183_reload),
    .din56(updated_dist_184_reload),
    .din57(updated_dist_185_reload),
    .din58(updated_dist_186_reload),
    .din59(updated_dist_187_reload),
    .din60(updated_dist_188_reload),
    .din61(updated_dist_189_reload),
    .din62(updated_dist_190_reload),
    .din63(updated_dist_191_reload),
    .din64(updated_dist_192_reload),
    .din65(updated_dist_193_reload),
    .din66(updated_dist_194_reload),
    .din67(updated_dist_195_reload),
    .din68(updated_dist_196_reload),
    .din69(updated_dist_197_reload),
    .din70(updated_dist_198_reload),
    .din71(updated_dist_199_reload),
    .din72(updated_dist_200_reload),
    .din73(updated_dist_201_reload),
    .din74(updated_dist_202_reload),
    .din75(updated_dist_203_reload),
    .din76(updated_dist_204_reload),
    .din77(updated_dist_205_reload),
    .din78(updated_dist_206_reload),
    .din79(updated_dist_207_reload),
    .din80(updated_dist_208_reload),
    .din81(updated_dist_209_reload),
    .din82(updated_dist_210_reload),
    .din83(updated_dist_211_reload),
    .din84(updated_dist_212_reload),
    .din85(updated_dist_213_reload),
    .din86(updated_dist_214_reload),
    .din87(updated_dist_215_reload),
    .din88(updated_dist_216_reload),
    .din89(updated_dist_217_reload),
    .din90(updated_dist_218_reload),
    .din91(updated_dist_219_reload),
    .din92(updated_dist_220_reload),
    .din93(updated_dist_221_reload),
    .din94(updated_dist_222_reload),
    .din95(updated_dist_223_reload),
    .din96(updated_dist_224_reload),
    .din97(updated_dist_225_reload),
    .din98(updated_dist_226_reload),
    .din99(updated_dist_227_reload),
    .din100(updated_dist_228_reload),
    .din101(updated_dist_229_reload),
    .din102(updated_dist_230_reload),
    .din103(updated_dist_231_reload),
    .din104(updated_dist_232_reload),
    .din105(updated_dist_233_reload),
    .din106(updated_dist_234_reload),
    .din107(updated_dist_235_reload),
    .din108(updated_dist_236_reload),
    .din109(updated_dist_237_reload),
    .din110(updated_dist_238_reload),
    .din111(updated_dist_239_reload),
    .din112(updated_dist_240_reload),
    .din113(updated_dist_241_reload),
    .din114(updated_dist_242_reload),
    .din115(updated_dist_243_reload),
    .din116(updated_dist_244_reload),
    .din117(updated_dist_245_reload),
    .din118(updated_dist_246_reload),
    .din119(updated_dist_247_reload),
    .din120(updated_dist_248_reload),
    .din121(updated_dist_249_reload),
    .din122(updated_dist_250_reload),
    .din123(updated_dist_251_reload),
    .din124(updated_dist_252_reload),
    .din125(updated_dist_253_reload),
    .din126(updated_dist_254_reload),
    .din127(updated_dist_255_reload),
    .din128(tmp_2_fu_1166_p129),
    .dout(tmp_2_fu_1166_p130)
);

bellman_ford_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln1027_fu_1150_p2 == 1'd0)) begin
            j_V_1_fu_318 <= add_ln840_fu_1156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_V_1_fu_318 <= 8'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln1027_fu_1150_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_j_V = 8'd0;
    end else begin
        ap_sig_allocacmp_j_V = j_V_1_fu_318;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        dist_0_ce0 = 1'b1;
    end else begin
        dist_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln1027_fu_1150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln48_fu_1432_p1 == 2'd0))) begin
        dist_0_we0 = 1'b1;
    end else begin
        dist_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        dist_1_ce0 = 1'b1;
    end else begin
        dist_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln1027_fu_1150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln48_fu_1432_p1 == 2'd1))) begin
        dist_1_we0 = 1'b1;
    end else begin
        dist_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        dist_2_ce0 = 1'b1;
    end else begin
        dist_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln1027_fu_1150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln48_fu_1432_p1 == 2'd2))) begin
        dist_2_we0 = 1'b1;
    end else begin
        dist_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        dist_3_ce0 = 1'b1;
    end else begin
        dist_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln1027_fu_1150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln48_fu_1432_p1 == 2'd3))) begin
        dist_3_we0 = 1'b1;
    end else begin
        dist_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln840_fu_1156_p2 = (ap_sig_allocacmp_j_V + 8'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign dist_0_address0 = zext_ln48_fu_1446_p1;

assign dist_0_d0 = tmp_2_fu_1166_p130;

assign dist_1_address0 = zext_ln48_fu_1446_p1;

assign dist_1_d0 = tmp_2_fu_1166_p130;

assign dist_2_address0 = zext_ln48_fu_1446_p1;

assign dist_2_d0 = tmp_2_fu_1166_p130;

assign dist_3_address0 = zext_ln48_fu_1446_p1;

assign dist_3_d0 = tmp_2_fu_1166_p130;

assign icmp_ln1027_fu_1150_p2 = ((ap_sig_allocacmp_j_V == 8'd128) ? 1'b1 : 1'b0);

assign lshr_ln3_fu_1436_p4 = {{ap_sig_allocacmp_j_V[6:2]}};

assign tmp_2_fu_1166_p129 = ap_sig_allocacmp_j_V[6:0];

assign trunc_ln48_fu_1432_p1 = ap_sig_allocacmp_j_V[1:0];

assign zext_ln48_fu_1446_p1 = lshr_ln3_fu_1436_p4;

endmodule //bellman_ford_bellman_ford_Pipeline_VITIS_LOOP_46_2
